<?php

namespace App\Infoexam\Paper;

use App\Infoexam\Core\Entity;
use Illuminate\Database\Eloquent\SoftDeletes;

class PaperList extends Entity
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['ssn', 'name', 'remark', 'auto_generate'];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    protected $ssn = true;

    public function questions()
    {
        return $this->belongsToMany('App\Infoexam\ExamSet\ExamQuestion', 'papers_questions')
            ->whereNull('papers_questions.deleted_at')
            ->withPivot('ssn');
    }

    public function test_lists()
    {
        return $this->hasMany('App\Infoexam\Test\TestList');
    }

    public function scopeAutoGenerated($query, $param)
    {
        $query->where('auto_generate', '=', (bool) $param);
    }
}