<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Infoexam\Paper\PaperList;
use App\Infoexam\Paper\PaperQuestion;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;

class PaperListsController extends Controller
{
    public function index(Request $request)
    {
        $title = trans('paper-lists.title');

        $auto_generated = $request->input('auto_generated', false);

        $paper_lists = PaperList::orderBy('id', 'desc')
            ->autoGenerated($auto_generated)
            ->paginate(10, ['ssn', 'name', 'remark', 'updated_at']);

        return view('admin.paper-lists.index', compact('title', 'auto_generated', 'paper_lists'));
    }

    public function create()
    {
        $title = trans('paper-lists.create');

        return view('admin.paper-lists.create', compact('title'));
    }

    public function store(Requests\Admin\PaperListsRequest $request)
    {
        PaperList::create($request->all());

        return redirect()->route('admin.paper-lists.index');
    }

    public function show($ssn)
    {
        try
        {
            $title = trans('paper-questions.list');

            $paper = PaperList::where('ssn', '=', $ssn)->firstOrFail();

            $questions = $paper->questions;

            return view('admin.paper-lists.show', compact('title', 'paper', 'questions'));
        }
        catch (ModelNotFoundException $e)
        {
            return http_404('admin.paper-lists.index');
        }

    }

    public function edit($ssn)
    {
        try
        {
            $title = trans('paper-lists.edit');

            $paper = PaperList::where('ssn', '=', $ssn)->firstOrFail();

            return view('admin.paper-lists.edit', compact('title', 'paper'));
        }
        catch (ModelNotFoundException $e)
        {
            return http_404('admin.paper-lists.index');
        }
    }

    public function update(Requests\Admin\PaperListsRequest $request, $ssn)
    {
        try
        {
            PaperList::where('ssn', '=', $ssn)->firstOrFail(['id'])->update($request->except(['ssn']));
        }
        catch (ModelNotFoundException $e)
        {
            http_404();
        }

        return redirect()->route('admin.paper-lists.index');
    }

    public function destroy($ssn)
    {
        try
        {
            $paper = PaperList::where('ssn', '=', $ssn)->firstOrFail();

            PaperQuestion::where('paper_list_id', '=', $paper->id)->delete();

            $paper->delete();
        }
        catch (ModelNotFoundException $e)
        {
            http_404();
        }

        return redirect()->route('admin.paper-lists.index');
    }
}